# Generated by Django 4.2.1 on 2023-06-15 23:45

import articles.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_formal', models.BooleanField(default=True)),
                ('size', models.FloatField(default=0.0)),
                ('next_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.block')),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('font_path', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date and time when the publication was published')),
                ('max_size', models.IntegerField(blank=True, null=True)),
                ('pdf_version', models.FileField(blank=True, null=True, upload_to=articles.models.user_directory_path)),
                ('html_version', models.FileField(blank=True, null=True, upload_to=articles.models.user_directory_path)),
                ('is_checked', models.BooleanField(default=False)),
                ('checks', models.ManyToManyField(related_name='checks', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='BlockDoi',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('doi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BlockImage',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('file_path', models.FileField(blank=True, null=True, upload_to=articles.models.directory_for_blocks)),
            ],
        ),
        migrations.CreateModel(
            name='BlockQuiz',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('name', models.TextField(blank=True, max_length=250, null=True)),
                ('is_formal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlockReferences',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockVideo',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('url', models.TextField(blank=True, max_length=250, null=True)),
                ('is_formal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('text', models.TextField(max_length=3500)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('keyword', models.TextField(blank=True, max_length=255, null=True)),
                ('publications', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='rates',
            field=models.ManyToManyField(related_name='rates', through='articles.Rate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.publication'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.questions')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.blockquiz'),
        ),
        migrations.CreateModel(
            name='BlockTitle',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_type', models.CharField(blank=True, default='1', max_length=2, null=True)),
                ('font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.font')),
            ],
        ),
        migrations.CreateModel(
            name='BlockText',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('text', models.TextField(blank=True, max_length=3500, null=True)),
                ('font_size', models.FloatField(blank=True, null=True)),
                ('font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.font')),
            ],
        ),
        migrations.CreateModel(
            name='BlockTable',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('text', models.TextField(max_length=3500)),
                ('font_size', models.FloatField()),
                ('font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.font')),
            ],
        ),
        migrations.CreateModel(
            name='BlockAuthors',
            fields=[
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.block')),
                ('authors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
