# Generated by Django 4.1.6 on 2023-05-30 14:07

import articles.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_formal", models.BooleanField(default=True)),
                ("size", models.FloatField(default=0.0)),
                (
                    "next_block_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('font_path', models.FileField(upload_to=articles.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name="BlockDoi",
            fields=[
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="articles.block",
                    ),
                ),
                ("doi", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BlockImage",
            fields=[
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="articles.block",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(upload_to=articles.models.user_directory_path),
                ),
                ("name", models.TextField(max_length=255)),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="BlockQuiz",
            fields=[
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="articles.block",
                    ),
                ),
                ("name", models.TextField(max_length=250)),
                ("is_formal", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BlockVideo",
            fields=[
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="articles.block",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("duration", models.IntegerField()),
                ("url", models.TextField(max_length=250)),
                ("is_formal", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pub_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="date and time when the publication was published",
                    ),
                ),
                ("max_size", models.IntegerField(blank=True, null=True)),
                (
                    "pdf_version",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=articles.models.user_directory_path,
                    ),
                ),
                (
                    "html_version",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=articles.models.user_directory_path,
                    ),
                ),
                (
                    "checks",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rates",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=350)),
                ('quiz_block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.blockquiz')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='rates',
            field=models.ManyToManyField(blank=True, null=True, related_name='rates', through='articles.Rate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(max_length=255)),
                ('publications', models.ManyToManyField(to='articles.publication')),
            ],
        ),
        migrations.CreateModel(
            name="BlockReferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("authors", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="block",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.questions')),
            ],
        ),
        migrations.AddField(
            model_name="questions",
            name="quiz_block_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.blockquiz"
            ),
        ),
        migrations.CreateModel(
            name="BlockTitle",
            fields=[
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="articles.block",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_type", models.CharField(blank=True, default="1", max_length=2)),
                (
                    "font",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.font",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockText",
            fields=[
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="articles.block",
                    ),
                ),
                ("text", models.TextField(blank=True, max_length=3500, null=True)),
                ("font_size", models.FloatField(blank=True, null=True)),
                (
                    "font",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.font",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockTable",
            fields=[
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="articles.block",
                    ),
                ),
                ("text", models.TextField(max_length=3500)),
                ("font_size", models.FloatField()),
                (
                    "font",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.font",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockAuthors",
            fields=[
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="articles.block",
                    ),
                ),
                ("authors", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
