# Generated by Django 4.1.6 on 2023-05-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="block",
            old_name="next_block_id",
            new_name="next_block",
        ),
        migrations.RenameField(
            model_name="block",
            old_name="publication_id",
            new_name="publication",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="quiz_block_id",
            new_name="quiz_block",
        ),
    ]
