# Generated by Django 4.1.6 on 2023-05-29 18:16

import articles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="checks",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="checks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="html_version",
            field=models.FileField(
                blank=True, null=True, upload_to=articles.models.user_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="max_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pub_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="date and time when the publication was published",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="rates",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="rates", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
