# Generated by Django 4.1.6 on 2023-06-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockvideo",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="blockvideo",
            name="name",
        ),
    ]
