# Generated by Django 4.1.6 on 2023-05-20 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockAuthors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_formal", models.BooleanField(default=True)),
                ("size", models.FloatField(default=0.0)),
                ("url_authors", models.TextField(max_length=250)),
                (
                    "next_block_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.blockauthors",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlockDoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_formal", models.BooleanField(default=True)),
                ("size", models.FloatField(default=0.0)),
                ("doi", models.CharField(max_length=255)),
                (
                    "next_block_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.blockdoi",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlockImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_formal", models.BooleanField(default=True)),
                ("size", models.FloatField(default=0.0)),
                ("file_path", models.FilePathField(path="/files/image")),
                ("name", models.TextField(max_length=255)),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "next_block_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.blockimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlockQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.FloatField(default=0.0)),
                ("name", models.TextField(max_length=250)),
                ("is_formal", models.BooleanField(default=False)),
                (
                    "next_block_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.blockquiz",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlockReferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_formal", models.BooleanField(default=True)),
                ("size", models.FloatField(default=0.0)),
                ("title", models.CharField(max_length=255)),
                ("authors", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "next_block_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.blockreferences",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlockTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_formal", models.BooleanField(default=True)),
                ("size", models.FloatField(default=0.0)),
                ("text", models.TextField(max_length=3500)),
                ("font_size", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlockText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_formal", models.BooleanField(default=True)),
                ("size", models.FloatField(default=0.0)),
                ("text", models.CharField(max_length=3500)),
                ("font_size", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlockTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_formal", models.BooleanField(default=True)),
                ("size", models.FloatField(default=0.0)),
                ("title", models.CharField(max_length=255)),
                ("font_size", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BlockVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.FloatField(default=0.0)),
                ("name", models.CharField(max_length=50)),
                ("duration", models.IntegerField()),
                ("url", models.TextField(max_length=250)),
                ("is_formal", models.BooleanField(default=False)),
                (
                    "next_block_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="articles.blockvideo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Font",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("font_path", models.FilePathField(path="/files/font")),
            ],
        ),
        migrations.CreateModel(
            name="Keywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=50)),
                (
                    "pub_date",
                    models.DateTimeField(
                        verbose_name="date and time when the publication was published"
                    ),
                ),
                ("max_size", models.IntegerField()),
                ("pdf_version", models.FilePathField(path="/files/pdf")),
                ("html_version", models.FilePathField(path="/files/html")),
                (
                    "checks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rates",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rated_publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(max_length=350)),
                (
                    "quiz_block_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.blockquiz",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="fieldimage",
            name="article",
        ),
        migrations.RemoveField(
            model_name="fieldimage",
            name="next",
        ),
        migrations.RemoveField(
            model_name="fieldtext",
            name="article",
        ),
        migrations.RemoveField(
            model_name="fieldtext",
            name="next",
        ),
        migrations.RemoveField(
            model_name="fieldvideo",
            name="article",
        ),
        migrations.RemoveField(
            model_name="fieldvideo",
            name="next",
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="FieldImage",
        ),
        migrations.DeleteModel(
            name="FieldText",
        ),
        migrations.DeleteModel(
            name="FieldVideo",
        ),
        migrations.AddField(
            model_name="keywords",
            name="publications",
            field=models.ManyToManyField(to="articles.publication"),
        ),
        migrations.AddField(
            model_name="blockvideo",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.AddField(
            model_name="blocktitle",
            name="font",
            field=models.ManyToManyField(blank=True, to="articles.font"),
        ),
        migrations.AddField(
            model_name="blocktitle",
            name="next_block_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blocktitle",
            ),
        ),
        migrations.AddField(
            model_name="blocktitle",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.AddField(
            model_name="blocktext",
            name="font",
            field=models.ManyToManyField(blank=True, to="articles.font"),
        ),
        migrations.AddField(
            model_name="blocktext",
            name="next_block_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blocktext",
            ),
        ),
        migrations.AddField(
            model_name="blocktext",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.AddField(
            model_name="blocktable",
            name="font",
            field=models.ManyToManyField(blank=True, to="articles.font"),
        ),
        migrations.AddField(
            model_name="blocktable",
            name="next_block_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blocktable",
            ),
        ),
        migrations.AddField(
            model_name="blocktable",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.AddField(
            model_name="blockreferences",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.AddField(
            model_name="blockquiz",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.AddField(
            model_name="blockimage",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.AddField(
            model_name="blockdoi",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.AddField(
            model_name="blockauthors",
            name="publication_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.publication"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="authors",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.blockauthors"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.questions"
            ),
        ),
    ]
