# Generated by Django 4.2.1 on 2023-06-16 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='checks',
            field=models.ManyToManyField(limit_choices_to={'available': True, 'groups__permissions__codename': 'is_checker'}, related_name='checks', to=settings.AUTH_USER_MODEL),
        ),
    ]
