# Generated by Django 4.1.6 on 2023-06-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_remove_blockvideo_duration_remove_blockvideo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockvideo",
            name="url",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
