# Generated by Django 4.1.6 on 2023-05-21 08:01

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_answer_author_blockauthors_blockdoi_blockimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockimage",
            name="file_path",
            field=models.FileField(upload_to=articles.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="font",
            name="font_path",
            field=models.FileField(upload_to=articles.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="publication",
            name="html_version",
            field=models.FileField(upload_to=articles.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pdf_version",
            field=models.FileField(
                blank=True, null=True, upload_to=articles.models.user_directory_path
            ),
        ),
    ]
