# Generated by Django 4.2.1 on 2023-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_publication_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
