# Generated by Django 4.2.1 on 2023-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_publication_is_editable_publication_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
