# Generated by Django 4.1.6 on 2023-06-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_blockvideo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockreferences",
            name="title",
        ),
    ]
