# Generated by Django 4.1.6 on 2023-05-31 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_remove_blockimage_height_remove_blockimage_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockreferences",
            name="id",
        ),
        migrations.AddField(
            model_name="blockreferences",
            name="block",
            field=models.OneToOneField(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="articles.block",
            ),
            preserve_default=False,
        ),
    ]
