# Generated by Django 4.1.6 on 2023-05-21 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0003_alter_blockimage_file_path_alter_font_font_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="checks",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checked_publications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="rates",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rated_publications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
