# Generated by Django 4.1.6 on 2023-05-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_publication_checks_alter_publication_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockauthors",
            name="next_block_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blockauthors",
            ),
        ),
        migrations.AlterField(
            model_name="blockdoi",
            name="next_block_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blockdoi",
            ),
        ),
        migrations.AlterField(
            model_name="blockimage",
            name="next_block_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blockimage",
            ),
        ),
        migrations.AlterField(
            model_name="blockquiz",
            name="next_block_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blockquiz",
            ),
        ),
        migrations.AlterField(
            model_name="blockreferences",
            name="next_block_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blockreferences",
            ),
        ),
        migrations.AlterField(
            model_name="blocktable",
            name="next_block_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blocktable",
            ),
        ),
        migrations.AlterField(
            model_name="blocktext",
            name="font_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blocktext",
            name="next_block_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blocktext",
            ),
        ),
        migrations.AlterField(
            model_name="blocktext",
            name="text",
            field=models.CharField(blank=True, max_length=3500, null=True),
        ),
        migrations.AlterField(
            model_name="blocktitle",
            name="next_block_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blocktitle",
            ),
        ),
        migrations.AlterField(
            model_name="blockvideo",
            name="next_block_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.blockvideo",
            ),
        ),
    ]
