# Generated by Django 4.1.6 on 2023-06-01 10:11

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_blockimage_file_path_alter_font_font_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockimage",
            name="file_path",
            field=models.FileField(
                blank=True, null=True, upload_to=articles.models.directory_for_blocks
            ),
        ),
    ]
