# Generated by Django 4.1.6 on 2023-05-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_blockauthors_next_block_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blocktext",
            name="font",
        ),
        migrations.AlterField(
            model_name="blocktext",
            name="text",
            field=models.TextField(blank=True, max_length=3500, null=True),
        ),
        migrations.AddField(
            model_name="blocktext",
            name="font",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.font",
            ),
        ),
    ]
