# Generated by Django 4.1.6 on 2023-06-10 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0005_alter_blockreferences_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockreferences",
            name="authors",
        ),
        migrations.AddField(
            model_name="blockreferences",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blockreferences",
            name="url",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="blockauthors",
            name="authors",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
