# Generated by Django 4.1.6 on 2023-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0006_remove_blockreferences_authors_blockreferences_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktitle",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="blocktitle",
            name="title_type",
            field=models.CharField(blank=True, default="1", max_length=2, null=True),
        ),
    ]
