# Generated by Django 4.1.6 on 2023-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_remove_keywords_id_remove_keywords_publications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywords",
            name="keyword",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
