# Generated by Django 4.1.6 on 2023-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_comments_alter_answer_answer_alter_blockquiz_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
