# Generated by Django 4.1.6 on 2023-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpersonalized",
            name="website",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
    ]
