# Generated by Django 4.2.1 on 2023-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_alter_userpersonalized_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalized',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
